# This configuration file should contain all required configuration parameters
# for the Nextclade workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values


# Define wildcards used for building trees in the workflow, also used in the intermediate files or auxillariary default file names.
# {group} represents different genotypes to be analyzed
groups: ['all']
# {gene} represents the norovirus genes to focus on in each build
genes: ['RdRp','VP1']

# Sequences must be FASTA and metadata must be TSV
# Both files must be zstd compressed
sequences_url: "https://data.nextstrain.org/files/workflows/norovirus/sequences.fasta.zst"
metadata_url: "https://data.nextstrain.org/files/workflows/norovirus/metadata.tsv.zst"

strain_id_field: "accession"
# Will be used to generate the group and gene level references
reference: ../phylogenetic/defaults/{group}/reference.gb

clade_membership:
  metadata: defaults/{gene}/clade_membership.tsv

filter:
  exclude: ../phylogenetic/defaults/exclude.txt
  include: defaults/{gene}/include.txt
  min_coverage: 0.8
  filter_params: --group-by year ORF2_type ORF1_type --sequences-per-group 10 --min-date 1950 --exclude-ambiguous-dates-by year --query-columns is_lab_host:str --exclude-where is_lab_host='true'

refine:
  root:
    default: best --timetree --date-confidence --clock-filter-iqd 4 --date-inference marginal
  # Estimated from auspice build https://github.com/nextstrain/norovirus/issues/22#issuecomment-3221851561
  clock_rate:
    all:
      RdRp: 0.00135
      VP1: 0.00136

traits:
  default: clade_membership genogroup genotype variant ORF1_type ORF2_type
  sampling_bias_correction: 3

colors:
  color_schemes: ../phylogenetic/defaults/color_schemes.tsv
  color_orderings: defaults/color_orderings.tsv

export:
  auspice_config: results/defaults/{group}/{gene}/auspice_config.json
  description: ../phylogenetic/defaults/description.md
